### ISSUE TITLE
Meetup #1 - Phuoc (@phuoc-ksis) - Mình đã học năm nhất như thế nào?

### ISSUE THREAD

**Issue by MaiPhuoc** [ks-is/meetup#2]
#### 1. Nhận thức trước và sau khi vào trường.
- Trước: Chưa biết nhiều về công nghệ thông tin, chỉ biết sử dụng máy tính để chơi game, đã từng nghiện game, không sử dụng máy tính nhiều trong cấp 3.
- Sau: Bị mê hoặc bơi máy tính, rất nhiều thứ cứ lôi kéo mình theo; không biết có đam mê hay không nhưng cứ theo đuổi 1 cái j đó, ban đầu dở thì chưa thích, khi biết biết rồi thì lần lần đâm ra thích nó, mê hoặc bởi nó :smile: 

Cũng đã từng so sánh trường mình với trường khác => ưu, khuyết => nhấn mạnh yếu tố con người là quan trọng nhất.
#### 2. Lập kế hoạch và quản lí thời gian (Nội dung chính)
- Xác định mục tiêu 
- Tìm động lực và cách để duy trì
- Quản lí thời gian

=> Đừng bỏ phí, dù chỉ 1 giây! (**Live each day as if it's your last. Cherish your friends, stay true to your principles, live passionately and fully and well. Experience new things. Love and be loved**)

**Comment by toanhv0x5e** [comment]
:+1:
